// Code generated by protoc-gen-zeropb. DO NOT EDIT.

package raftzeropb

import "github.com/danhhz/zeropb"

type Entry struct {
  buf []byte
  offsets zeropb.FastIntMap
}

func (m *Entry) Decode(buf []byte) error{
  m.buf = buf
  return zeropb.Decode(m.buf, &m.offsets)
}

func (m *Entry) Term() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 2)
}

func (m *Entry) Index() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 3)
}

func (m *Entry) Type() uint32 {
  return zeropb.GetUint32(m.buf, &m.offsets, 1)
}

func (m *Entry) Data() []byte {
  return zeropb.GetBytes(m.buf, &m.offsets, 4)
}

type SnapshotMetadata struct {
  buf []byte
  offsets zeropb.FastIntMap
}

func (m *SnapshotMetadata) Decode(buf []byte) error{
  m.buf = buf
  return zeropb.Decode(m.buf, &m.offsets)
}

func (m *Message) ConfState(x *ConfState) (bool, error) {
  buf := zeropb.GetBytes(m.buf, &m.offsets, 1)
  if buf == nil {
    return false, nil
  }
  return true, x.Decode(buf)
}

func (m *SnapshotMetadata) Index() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 2)
}

func (m *SnapshotMetadata) Term() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 3)
}

type Snapshot struct {
  buf []byte
  offsets zeropb.FastIntMap
}

func (m *Snapshot) Decode(buf []byte) error{
  m.buf = buf
  return zeropb.Decode(m.buf, &m.offsets)
}

func (m *Snapshot) Data() []byte {
  return zeropb.GetBytes(m.buf, &m.offsets, 1)
}

func (m *Message) Metadata(x *SnapshotMetadata) (bool, error) {
  buf := zeropb.GetBytes(m.buf, &m.offsets, 2)
  if buf == nil {
    return false, nil
  }
  return true, x.Decode(buf)
}

type Message struct {
  buf []byte
  offsets zeropb.FastIntMap
}

func (m *Message) Decode(buf []byte) error{
  m.buf = buf
  return zeropb.Decode(m.buf, &m.offsets)
}

func (m *Message) Type() uint32 {
  return zeropb.GetUint32(m.buf, &m.offsets, 1)
}

func (m *Message) To() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 2)
}

func (m *Message) From() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 3)
}

func (m *Message) Term() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 4)
}

func (m *Message) LogTerm() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 5)
}

func (m *Message) Index() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 6)
}

type MessageEntryIterator []byte

func (i *MessageEntryIterator) Next(m *Entry) (bool, error) {
  var buf []byte
  *i, buf = zeropb.FindNextField((*i), 7)
  if buf == nil {
    return false, nil
  }
  return true, m.Decode(buf)
}

func (m *Message) Entries() MessageEntryIterator {
  return MessageEntryIterator(zeropb.GetRepeatedMessage(m.buf, &m.offsets, 7))
}

func (m *Message) Commit() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 8)
}

func (m *Message) Snapshot(x *Snapshot) (bool, error) {
  buf := zeropb.GetBytes(m.buf, &m.offsets, 9)
  if buf == nil {
    return false, nil
  }
  return true, x.Decode(buf)
}

func (m *Message) RejectHint() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 11)
}

func (m *Message) Context() []byte {
  return zeropb.GetBytes(m.buf, &m.offsets, 12)
}

type HardState struct {
  buf []byte
  offsets zeropb.FastIntMap
}

func (m *HardState) Decode(buf []byte) error{
  m.buf = buf
  return zeropb.Decode(m.buf, &m.offsets)
}

func (m *HardState) Term() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 1)
}

func (m *HardState) Vote() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 2)
}

func (m *HardState) Commit() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 3)
}

type ConfState struct {
  buf []byte
  offsets zeropb.FastIntMap
}

func (m *ConfState) Decode(buf []byte) error{
  m.buf = buf
  return zeropb.Decode(m.buf, &m.offsets)
}

func (m *ConfState) Nodes() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 1)
}

func (m *ConfState) Learners() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 2)
}

type ConfChange struct {
  buf []byte
  offsets zeropb.FastIntMap
}

func (m *ConfChange) Decode(buf []byte) error{
  m.buf = buf
  return zeropb.Decode(m.buf, &m.offsets)
}

func (m *ConfChange) ID() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 1)
}

func (m *ConfChange) Type() uint32 {
  return zeropb.GetUint32(m.buf, &m.offsets, 2)
}

func (m *ConfChange) NodeID() uint64 {
  return zeropb.GetUint64(m.buf, &m.offsets, 3)
}

func (m *ConfChange) Context() []byte {
  return zeropb.GetBytes(m.buf, &m.offsets, 4)
}

